name: palmiche
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pip
  - python==3.9.*
  - nbsphinx
  - sphinx==5.3.0
  - conda-build
  - openbabel
  # - ambertools
  # - openff-toolkit
  # - openmm
  - pip:
    - pubchempy
    - tqdm
    - numpy
    - pandas
    - scikit-learn
    - kmodes
    - kneed
    - uncertainties
    - prolif
    - scipy
    - rdkit
    - seaborn
    - pytest
    - sphinx_copybutton
    - myst_nb
    - recommonmark
    - sphinx_book_theme